modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]
modId = "yourstageskybox"
version = "${file.jarVersion}"
displayName = "YourStageSkybox"
description = '''
提供API和指令，供地图创作者快捷可控地切换天空盒材质。
Provides API and commands for map creators to switch skybox textures at runtime.
'''
authors = ""

[[dependencies.yourstageskybox]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.yourstageskybox]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1]"
    ordering = "NONE"
    side = "BOTH"
